server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能，利用微服务名称进行路由
      routes:
        - id: payment_route # 路由的id,没有规定规则但要求唯一,建议配合服务名
          #匹配后提供服务的路由地址
#          uri: http://localhost:8001
          uri: lb://cloud-payment-service     # lb 是负载均衡的意思
          predicates:
            - Path=/payment/get/** # 断言，路径相匹配的进行路由

        - id: payment_route2
#          uri: http://localhost:8001
          uri: lb://cloud-payment-service
          predicates:                                                  # 说白了。predicate就是为了实现一组匹配规则，让请求过来找到对应的Route进行处理
          - Path=/payment/lb/** #断言,路径相匹配的进行路由
          - After=2020-03-12T15:44:15.064+08:00[Asia/Shanghai]          # 时间和地址都要匹配成功，才会走网关,通过 ZonedDateTime 实现类实现
#          - Cookie=username,luzc   #带Cookie，并且username的值为luzc    # 此时请求地址为  http://localhost:9527/payment/lb --cookie "username=luzc"
#          - Header=X-Request-Id,\d+ #请求头要有 X-Request-Id属性并且值为整数的正则表达式     http://localhost:9527/payment/lb -H “X-Request-Id:123"

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
